### ISSUE TITLE
OL NumpyTiles Projection Support

### ISSUE THREAD

**Issue by rbudhu** [planetlabs/ol-numpytiles#8]
Hi!  Does ol-numpytiles support EPSG:4326 WGS84 projection?  I modified the demo index.js to use EPSG:4326 projection (as it seems like NumpySource accepted other projections as arguments) and the demo ceased to work -- the OSM basemap could be seen, but my COG image was not tiled in.  I'm using TiTiler for my COG server and I made modifications to index.js as follows:

```
const numpySource = new NumpySource({
  url:
    'http://XXXXXXX/cog/tiles/WorldCRS84Quad/{z}/{x}/{y}@1x?url=\
' +
    encodeURIComponent(COG) +
    '&format=npy',
  dtype: 'uint16',
  bands: ['b', 'g', 'r', 'n', 'a'],
    pixelDepth: 65535,
    projection: 'EPSG:4326',
});
```

```
function init() {
  new olMap({
    target: document.getElementById('map'),
    layers: [
      new TileImageLayer({
        source: new OSM(),
      }),
      numpyLayer,
    ],
    view: new View({
      center: [99.788242, 40.399644],
        zoom: 15,
        projection: 'EPSG:4326'
    }),
  });
```

If I change everything to EPSG:3857 and WebMercatorQuad, it all works again.  Thanks!

**Comment by theduckylittle** [comment]
Hi @rbudhu,

We have not done a lot of testing using projections other than 3857.

Can you  first verify that TiTiler is returning a valid NumpyTile?

Thanks!

**Comment by rbudhu** [comment]
Hi @theduckylittle:

Yes, it seems like TiTiler is returning a valid NumpyTile using the WorldCRS84Quad tile matrix set.  Here is a link to one of the tiles that get returned: [https://easyupload.io/vdp0kq](https://easyupload.io/vdp0kq)

The header looks like the following, followed by the numpy binary data.

```
“NUMPY {'descr': '<u2', 'fortran_order': False, 'shape': (5, 256, 256), }                                                   
```

**Comment by theduckylittle** [comment]
I'm trying to get a test-case working. I've found the following:

1. The way numpy tiles are rendered does not currently support client-side raster re-projection but the parent class thinks it does. I think if you look at the network inspector you'll see that tiles are still being fetched with WebMercator tile coordinates (especially for OSM).
2. When I disable re-projection in `NumpySource` then TiTiler continually complains that my COG is out of bounds, even when doing a global view. So there might be a bug there as well.

I'll see if I can make some more time to look at this.

**Comment by rbudhu** [comment]
Thanks!  This is a really great library.  I will also look into the TiTiler out of bounds issue.
